# One CLI to format the code tree - https://github.com/numtide/treefmt

[formatter.nix]
command = "nixpkgs-fmt"
includes = [ "*.nix"]

[formatter.python]
command = "black"
includes = ["*.py"]

[formatter.media]
command = "prettier"
options = ["--write"]
includes = [
    "*.json",
    "*.md",
    "*.yaml",
    "*.yml",
]
