name: check
on: [push, pull_request]
jobs:
  checker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - uses: cachix/install-nix-action@v31

      - name: nix run .#check
        run: nix run .#check
